language: node_js

node_js:
  - "8"
  - "10"
  - "12"
  - "13"

env:
  env:
    global:
      # SERVERLESS_ACCESS_KEY (`ci` token in 1password)
      - secure: "IhpN2RSDv7GuyYSvz6YVaqji7RgnnmzsDe3Dn6zT3HjwEFmvZHMaHRKhkt2/jE1OaxIXESftbM0O6OsY+9qIFzPlgN7hNEYWJnj9rrQOlqJ43OJ/fzuefeMqCvU9cjolH0qe1Qs2kqYrVig/7uwtdAmkPw+NoCNt+9H8JtaD7wGCuxY5cbiK5eNVu8Yslt8oAFyi9zDGHYa1git2qzFWAxnCIsmBCZyljEEs5k53HZHGfmRaGq/5hlLN/5+gVt1vGejz769f7zhz01JPTh4GvFevcwx+8qOaHaHAuWI/4AOKQLa8L6AW6Trwencafgg50m0TCvo2CjCDXgBE8cGimxjw2vM5cDrBbm/lxPJL2S04gLCjoiXUCOcH0s870AgZsNCNKvygBLt2YBEyNEeIhU3+DLxfMns2c+G4DQcxybLj1FxLxycf7HebyU7FR1NEOtE6jKEHykCI7h8th4Swg1KaX3IOR5BjLvCpKg4psDnhpxvgraeWWQIZAXLpas3owRqGntDFcLIz6kXQAxQfIMM0AgHD9HtpSsmM2FeMkK+HMVeGkHdMA3oxFWEAPdK6mV0mL6hcU+nvgORWjO1wjQcIEaBFN9HgwXGVyrkZppa+bR0IXUYnQFJFAqirp9R/864husQS836MFhRFvGKlsmo0iUoTWuvaXLErLF9vii8="

branches:
  only:
    - master

install:
  # Get a more modern yarn.
  - npm install --global yarn@latest
  # Fail if lockfile outdated.
  # https://yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-frozen-lockfile
  - yarn install --frozen-lockfile

script:
  - yarn --version
  - yarn run check
  - yarn benchmark:build
  - yarn check:git-dirty
  - yarn benchmark:install
  - yarn test:cli
  - TEST_PARALLEL=true yarn benchmark
  - yarn benchmark:test
